---
title: "Sales Tracking"
type: "exercise"
description: "writing a while loop that tracks sales input until reaching $100!"
tags: "meta, looping"
visibility: "confirm"
ignore:
- "sales_tracking.md"
